FROM node:11.14-slim as builder

WORKDIR /app/
COPY . .
RUN yarn
RUN yarn build

FROM arm32v7/nginx:1.15

COPY qemu-arm-static /usr/bin/qemu-arm-static

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build/ /var/www/

EXPOSE 80
