const SET_EDITED_SEQUENCE_TITLE = "SET_EDITED_SEQUENCE_TITLE";
const SET_EDITED_SEQUENCE_COMMANDS = "SET_EDITED_SEQUENCE_COMMANDS";
const REMOVE_COMMAND_FROM_SEQUENCE = "REMOVE_COMMAND_FROM_SEQUENCE";
const CHANGE_WAIT_TIME = "CHANGE_WAIT_TIME";
const ADD_COMMAND_TO_SEQUENCE = "ADD_COMMAND_TO_SEQUENCE";

export default {
  SET_EDITED_SEQUENCE_COMMANDS,
  SET_EDITED_SEQUENCE_TITLE,
  REMOVE_COMMAND_FROM_SEQUENCE,
  CHANGE_WAIT_TIME,
  ADD_COMMAND_TO_SEQUENCE
};
