version: "3"
services:
  nodeserver:
    build: .
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true
  reactserver:
    build: ./client
    ports:
      - "8080:80"
    tty: true
    stdin_open: true
